---
title: "Basic Tree Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic Tree Simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(scTreeSim)
library(ggtree)
library(dplyr) # fix
set.seed(12)

```
## Single-type trees
Two options: by time of origin or by number of (extant) taxa
```{r}
shape <- 100
av_lifetime <- 1
d <- 0.08
scale <- av_lifetime/shape
t_or <- 6
ntaxa <- 2^6 
# simulate:
dat1 <- sim_adb_origin_complete(t_or, scale, shape, d)
dat2 <- sim_adb_ntaxa_complete(ntaxa, scale, shape, d)

dat1
```
Object returned is a treedata object (from treeio).

### Visualize
 Note: extinct lineages will show here
  
```{r, fig.show="hold", out.width="40%"}
plot(dat1@phylo, show.tip.label=FALSE, root.edge=TRUE)
plot(dat2@phylo, show.tip.label=FALSE, root.edge=TRUE)
```

### Sampled tree
 this also prunes extinct lineages

```{r, fig.show="hold", out.width="40%"}
rho <- 0.5 # sampling at present
dat1 <- sim_adb_origin_samp(t_or, scale, shape, d, rho)
dat2 <- sim_adb_ntaxa_samp(ntaxa, scale, shape, d, rho)

plot(dat1@phylo, show.tip.label=FALSE, root.edge=FALSE)
plot(dat2@phylo, show.tip.label=FALSE, root.edge=FALSE) 

```

## Multi-type trees

```{r, fig.show="hold", out.width="40%"}
# parameters
ntype <- 2
origin_type <- 0
shape <- c(100,100)
av_lifetime <- rep(1, ntype)
scale <- av_lifetime/shape
rho <- 0.8
t_or <- 7 
d <- c(0.01, 0.7)
# transition matrices
r <- 0.2
Xi_as <- matrix(c(0.0, 0.0, r, 0.0), nrow=ntype, ncol=ntype)
Xi_s <- matrix(c(1-r, 0.0, 0.0, 1.0), nrow=ntype, ncol=ntype)

dat1 <- sim_adb_origin_samp(t_or, scale, shape, d, rho, origin_type, Xi_as, Xi_s, collapse=F)

# another example
r <- 0.11
Xi_as <- matrix(c(0.0, 0.0, r, 0.0), nrow=ntype, ncol=ntype)
Xi_s <- matrix(c(1-r, 0.0, 0.0, 1.0), nrow=ntype, ncol=ntype)
d <- c(0.1, 0.1)
shape <- c(100, 1)
scale <- av_lifetime/shape
dat2 <- sim_adb_origin_samp(t_or, scale, shape, d, rho, origin_type, Xi_as=Xi_as, Xi_s=Xi_s, collapse=F)

# plot with node/tip types
ggtree(dat1, aes(color=type)) + geom_rootedge(color="#F8766D") + geom_tippoint()
ggtree(dat2, aes(color=type)) + geom_rootedge(color="#F8766D") + geom_tippoint()
```
