// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sim_adb_loop_cpp
List sim_adb_loop_cpp(int ntaxa, NumericVector scale, NumericVector shape, NumericVector death_prob, NumericMatrix asym_trans_prob, NumericMatrix sym_trans_prob, int origin_type);
RcppExport SEXP _scTreeSim_sim_adb_loop_cpp(SEXP ntaxaSEXP, SEXP scaleSEXP, SEXP shapeSEXP, SEXP death_probSEXP, SEXP asym_trans_probSEXP, SEXP sym_trans_probSEXP, SEXP origin_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntaxa(ntaxaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type death_prob(death_probSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type asym_trans_prob(asym_trans_probSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sym_trans_prob(sym_trans_probSEXP);
    Rcpp::traits::input_parameter< int >::type origin_type(origin_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_adb_loop_cpp(ntaxa, scale, shape, death_prob, asym_trans_prob, sym_trans_prob, origin_type));
    return rcpp_result_gen;
END_RCPP
}
// sim_adb_origin_loop_cpp
List sim_adb_origin_loop_cpp(double origin_time, NumericVector scale, NumericVector shape, NumericVector death_prob, NumericMatrix asym_trans_prob, NumericMatrix sym_trans_prob, int origin_type);
RcppExport SEXP _scTreeSim_sim_adb_origin_loop_cpp(SEXP origin_timeSEXP, SEXP scaleSEXP, SEXP shapeSEXP, SEXP death_probSEXP, SEXP asym_trans_probSEXP, SEXP sym_trans_probSEXP, SEXP origin_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type origin_time(origin_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type death_prob(death_probSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type asym_trans_prob(asym_trans_probSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sym_trans_prob(sym_trans_probSEXP);
    Rcpp::traits::input_parameter< int >::type origin_type(origin_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_adb_origin_loop_cpp(origin_time, scale, shape, death_prob, asym_trans_prob, sym_trans_prob, origin_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scTreeSim_sim_adb_loop_cpp", (DL_FUNC) &_scTreeSim_sim_adb_loop_cpp, 7},
    {"_scTreeSim_sim_adb_origin_loop_cpp", (DL_FUNC) &_scTreeSim_sim_adb_origin_loop_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_scTreeSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
