# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_adb_loop_cpp <- function(ntaxa, a, b, d, origin_type = 0L) {
    .Call(`_scTreeSim_sim_adb_loop_cpp`, ntaxa, a, b, d, origin_type)
}

sim_adb_origin_loop_cpp <- function(origin_time, a, b, d, origin_type = 0L) {
    .Call(`_scTreeSim_sim_adb_origin_loop_cpp`, origin_time, a, b, d, origin_type)
}

